### ISSUE TITLE
IEventDispatcher and mapSingletonOf

### ISSUE THREAD

**Issue by darscan** [tschneidereit/SwiftSuspenders#29]
This explodes:

injector.mapSingletonOf(IEventDispatcher, EventDispatcher);
injector.getInstance(IEventDispatcher);

**Comment by darscan** [comment]
It's not strictly the getInstance call that explodes, the same thing happens during property/setter injection.

**Comment by tschneidereit** [comment]
That's because the ctor of EventDispatcher has an optional parameter "target" of type IEventDispatcher, causing SwiftSuspenders to try to inject the very dependency it is in the process of creating.

Thus, instances of EventDispatcher are created ad infinitum. (Technically until the stack overflows because Adobe are sissies that don't want Flash to use up the entire memory of your computer in the span of a few microseconds.)

I'm afraid there's nothing I can do about that: You'll have to use mapValue when mapping IEventDispatcher.

**Comment by darscan** [comment]
Ha! I should have looked a little deeper, thanks for the response :)

**Comment by tschneidereit** [comment]
No problem :) Had to write a test-case myself before I realized what's going on.
