### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by darscan** [tschneidereit/SwiftSuspenders#80]
Howdy.

Currently the version in the build properties file of Swiftsuspenders we have `v2.0.0rc2stray2`, but in the latest RL2 libs folder we have a dependency on `Swiftsuspenders-v2.0.0rc3stray1`.

However, in the RL2 properties file we seem to be depending on `Swiftsuspenders-v2.0.0rc3stray1`.  And then in the Maven POM we're depending on `2.0.0-b4`, and in our Buildr buildfile we're depending on `Swiftsuspenders-v2.0.0rc3stray1.swc`!

Have @Stray's changes been merged in? Should the version be bumped to v2.0.0rc3?

**Comment by Stray** [comment]
Yeah… sorry for all that confusion - been hoping Till would pull/merge/part-reject my pull request and release. As far as I know, they have not yet been merged sufficient to swap in a Till-build.
v2.0.0rc3stray1 is the 'right' version (if Till strips out an optional param from instantiateUnmapped it shouldn't affect the framework). Apologies for not updating the Maven POM…  the others should (and appear to) all be consistent with rc3stray1.

Sx

**Comment by darscan** [comment]
No problem at all - was just prepping all the buildfiles for a snapshot release, and wasn't sure what was potting. Locally I've been building RL2 against the head of this repo, and I haven't come across any problems or failing tests. Maybe your changes have been pulled in?

**Comment by darscan** [comment]
Besides, the POM is a funny one as there are actually two scrips (*nix and win) that install the SWC files from the libs folder into your local Maven repository with specific version numbers. So, the file in the lib folder ends up being installed locally as `2.0.0-b4` - which is what the POM depends on.

**Comment by Stray** [comment]
I don't think they have yet - they only affect deeply-nested injections so I don't think the RL2 tests cover the changes.

**Comment by darscan** [comment]
Interesting.. perhaps that is why I've had injections injected as null without exploding - as I'm linking against the source and not the SWC.

**Comment by Stray** [comment]
Yup - unmapped should explode now unless you explicitly set a fallbackProvider or are using instantiateUnmapped();

The last set of changes affect the behaviour of instantiation of unmapped classes with dependency trees.

The last remaining controversy (afaik) is whether instantiateUnmapped needs a second optional param to tell you to also ignore mappings for the dependency tree. As Till rightly points out, you can just make a new injector with no mappings and a fallbackProvider to do this (as the injector does under the hood), but I think that could force folk to be injecting 2 named injectors around, which feels a bit icky. (To avoid the new Injector() overhead).

But I'll leave that to be determined… :)

Hrm… the only thing making me doubt this now (it being cause for your nulls) is that the newest commits of RL2 use methods that weren't available in SwiftSuspenders prior to October, though the deep-nested problem has only been fixed since then.

Curious...
