### ISSUE TITLE
mapSingletonOf slightly broken?

### ISSUE THREAD

**Issue by sfunke** [tschneidereit/SwiftSuspenders#9]
Hi Till,

just upgraded to SwiftSuspenders-1.0RC5 and find mapSingletonOf somehow broken:

This is the code that used to work with an oder version (1 month or so):

// full access interface for use in Commands
injector.mapSingletonOf(IVideoModel, VideosModel);
// readOnly interface for use in mediators (just to retrieve data)
injector.mapSingletonOf(IVideoModel_RO, VideosModel);

Both IVideoModel and IVideoModel_RO referenced the very same instance of VideosModel (same id in Debugger).

Since I've upgraded, thats no more true.. I have now two different instances of VideosModel lying around (different ids).

As a workaround, I've tested the mapVaule approach and it on the other hand still works as expected:

var videosModel:VideosModel = new VideosModel();
injector.mapValue(IVideoModel, videosModel);
injector.mapValue(IVideoModel_RO, videosModel);

So, my project isn't broken, but maybe there is something you could check?

Thanks - and thumbs up for SwiftSuspenders! :-)

Steffen

**Comment by tschneidereit** [comment]
Hey Steffen,

sorry about that change in behavior! The way it used to work was actually an accident - most of the time one would want different singleton instances for the different mapping rules - at least that's what I and the people on the Robotlegs mailing list think.

Anyway, your usecase is important as well, so I added support for that by introducing Injector#mapRule, which can be used like this:
var rule : \* = injector.mapSingletonOf(IVideoModel, VideosModel);
injector.mapRule(IVideoModel_RO, rule);

Using mapRule, you re-gain the advantage of having the singleton instance be initialized lazily on first access instead of having to create it manually before doing the mapping.

This is all in the current RC and thoroughly tested, I'm just a little behind on the documentation - sorry for that. And sorry for the "*" return type of the map methods  - there's just no other way to integrate cleanly with Robotlegs without adding circular dependencies (i.e. Robotlegs depending on SwiftSuspenders and vice versa).

And thanks for the kind words - much appreciated!

cheers,
till

**Comment by sfunke** [comment]
Ah I see - mapRule is a good one! Works!

Thank you for your quick reply and pointing out the intention behind!
I'm using Robotlegs as well so everything is fine now :-)

Thanks again,
Steff
